In [5]:
import pandas as pd
df=pd.DataFrame({"Name":["Braud","Allen","Bornell"],"Age":[22,35,58],"Sex":["male","male","female"]})
df

      Name  Age     Sex
0    Braud   22    male
1    Allen   35    male
2  Bornell   58  female

In [6]:
df["Sex"]

0      male
1      male
2    female
Name: Sex, dtype: str

In [7]:
df["Age"].max()

np.int64(58)

In [8]:
df.describe() #displaying all relevant statistics on numerical data

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

In [9]:
df["Age"].min() #finding the minimum age

np.int64(22)

In [2]:
import pandas as pd
titanic=pd.read_csv("data/Titanic-Dataset.csv") #importing titanic data
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [4]:
ages=titanic["Age"] #how to select a specific column in a dataset
ages.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [5]:
age_sex=titanic[["Age","Sex"]] #to select to specific columns in a dataset.
age_sex.head()

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

In [6]:
type(titanic[["Age", "Sex"]]) #to check the data type of the returned data .We will review.

pandas.DataFrame

In [7]:
age_sex.shape #to know number of rows and columns

(891, 2)

In [8]:
above_35=titanic[titanic["Age"]>35] #checking passengers above 35 years
above_35.head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
1              2         1       1
6              7         0       1
11            12         1       1
13            14         0       3
15            16         1       2
..           ...       ...     ...
865          866         1       2
871          872         1       1
873          874         0       3
879          880         1       1
885          886         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
6                              McCarthy, Mr. Timothy J    male  54.0      0
11                            Bonnell, Miss. Elizabeth  female  58.0      0
13                         Andersson, Mr. Anders Johan    male  39.0      1
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0
..                                                 ...     ...   ...    ...
865                           Bystrom, Mrs. (Karolina)  female  42.0      0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
873                        Vander Cruyssen, Mr. Victor    male  47.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0

     Parch    Ticket     Fare Cabin Embarked
1        0  PC 17599  71.2833   C85        C
6        0     17463  51.8625   E46        S
11       0    113783  26.5500  C103        S
13       5    347082  31.2750   NaN        S
15       0    248706  16.0000   NaN        S
..     ...       ...      ...   ...      ...
865      0    236852  13.0000   NaN        S
871      1     11751  52.5542   D35        S
873      0    345765   9.0000   NaN        S
879      1     11767  83.1583   C50        C
885      5    382652  29.1250   NaN        Q

[217 rows x 12 columns]>

In [9]:
class_23=titanic[titanic["Pclass"].isin([2,3])] #check titanic passengers from cabin class 2 and 3
class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [10]:
age_no_na=titanic[titanic["Age"].notna()] #passenger which age is known
age_no_na.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
age_no_na.shape

(714, 12)

In [12]:
adult_names=titanic.loc[titanic["Age"]>35,"Name"] #names of passengers older than 35.
adult_names.head()

1     Cumings, Mrs. John Bradley (Florence Briggs Th...
6                               McCarthy, Mr. Timothy J
11                             Bonnell, Miss. Elizabeth
13                          Andersson, Mr. Anders Johan
15                     Hewlett, Mrs. (Mary D Kingcome)
Name: Name, dtype: str

In [13]:
class_23=titanic[(titanic["Pclass"]==2)|(titanic["Pclass"]==3)] #using the
class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [14]:
age_is_na=titanic[titanic["Age"].isna()] #to return a list of passengers with ages missing. NaN in pandas means null. isna() is the method used to return rows with the missing values in pandas.
age_is_na.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

In [15]:
age_is_na.shape

(177, 12)

In [16]:
adult_names=titanic.loc[titanic["Age"]>=18,["Name", "Age"]]#.loc is used for selecting specific rows and columns
adult_names.head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0